properties
# Standard memory settings (Stable for most PCs)
org.gradle.jvmargs=-Xmx3G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Use AndroidX for libraries
android.useAndroidX=true
android.enableJetifier=true

# Speed up builds
org.gradle.parallel=true
org.gradle.caching=true